#!/usr/bin/env bats
# The generated Steam launcher. Every line in it is load-bearing under Steam, so
# these assert the workarounds are present rather than just that a file appeared.

bats_require_minimum_version 1.5.0

load helper

setup() {
  setup_env
  start_server
  write_config
  # A stand-in emulator, so install does not have to build a real one.
  export FAKE_EMU="$TEST_TMP/state/roots/fake"
  mkdir -p "$FAKE_EMU/bin"
  # Absolute shebang: /usr/bin/env does not exist inside the nix build sandbox.
  {
    printf '#!%s\n' "$(command -v bash)"
    printf 'echo "launched with: $*"\n'
  } >"$FAKE_EMU/bin/fake-emu"
  chmod +x "$FAKE_EMU/bin/fake-emu"

  jq -n '{fake: {attr: "hello", bin: "fake-emu", argsTemplate: ["{target}"]}}' \
    >"$TEST_TMP/emulators.json"
  jq -n '{n64: {emulator: "fake"}}' >"$TEST_TMP/platforms.json"
  cp -r "$(dirname "$GOTG_BIN")/../share/gotg/data" "$TEST_TMP/data"
  chmod -R u+w "$TEST_TMP/data"
  cp "$TEST_TMP/emulators.json" "$TEST_TMP/data/emulators.json"
  cp "$TEST_TMP/platforms.json" "$TEST_TMP/data/platforms.json"
  echo '{}' >"$TEST_TMP/data/overrides.json"
  export GOTG_DATA="$TEST_TMP/data"
}

teardown() {
  stop_server
}

@test "install writes an executable launcher next to the game" {
  add_game n64 "usa.zelda.z64" "rom" "Zelda"
  gotg refresh
  gotg install usa.zelda
  [ "$status" -eq 0 ]

  local launcher="$GOTG_GAMES_DIR/n64/play-usa.zelda.sh"
  [ -x "$launcher" ]
  [[ "$stderr" == *"$launcher"* ]]
}

@test "the launcher carries every Steam workaround" {
  add_game n64 "usa.zelda.z64" "rom" "Zelda"
  gotg refresh
  gotg install usa.zelda
  local launcher="$GOTG_GAMES_DIR/n64/play-usa.zelda.sh"

  # Steam gives a minimal PATH, so nix has to be findable.
  grep -q 'run/current-system/sw/bin' "$launcher"
  # Steam suppresses SDL controller detection for non-Steam apps.
  grep -q 'SDL_JOYSTICK_HIDAPI=0' "$launcher"
  grep -q 'unset SDL_GAMECONTROLLER_IGNORE_DEVICES' "$launcher"
  # The overlay's LD_PRELOAD breaks nix wrapper scripts.
  grep -q 'unset LD_PRELOAD' "$launcher"
  # Steam swallows output, so each launch has to leave a log.
  grep -q 'gotg/logs/usa.zelda.log' "$launcher"
  # gotg is called by absolute path; PATH lookup is unreliable under Steam.
  grep -q 'state}/gotg/app/bin/gotg' "$launcher"
  grep -q 'play "usa.zelda"' "$launcher"
}

@test "the launcher passes a platform-qualified id when one is needed" {
  add_game n64 "usa.bugs_life.zip" "n64"
  add_game snes "usa.bugs_life.zip" "snes"
  gotg refresh
  gotg install n64/usa.bugs_life
  [ "$status" -eq 0 ]

  grep -q 'play "n64/usa.bugs_life"' "$GOTG_GAMES_DIR/n64/play-usa.bugs_life.sh"
}

@test "a hand-written launcher is backed up, never overwritten" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  mkdir -p "$GOTG_GAMES_DIR/n64"
  local launcher="$GOTG_GAMES_DIR/n64/play-usa.zelda.sh"
  echo '#!/bin/bash: my careful hand-tuned script' >"$launcher"

  gotg install usa.zelda
  [ "$status" -eq 0 ]
  [ -f "$launcher.bak" ]
  grep -q 'hand-tuned' "$launcher.bak"
  grep -q 'generated by gotg' "$launcher"
}

@test "regenerating does not pile up backups of our own launchers" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  gotg install usa.zelda
  gotg install usa.zelda
  [ "$status" -eq 0 ]
  [ ! -e "$GOTG_GAMES_DIR/n64/play-usa.zelda.sh.bak" ]
}

@test "play launches the emulator with the game as its argument" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  gotg download usa.zelda
  gotg play usa.zelda
  [ "$status" -eq 0 ]
  [[ "$output" == *"launched with: $GOTG_GAMES_DIR/n64/usa.zelda.z64"* ]]
}

@test "play refuses to build an emulator, and says where to do it" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  gotg download usa.zelda
  rm -rf "$FAKE_EMU"

  gotg play usa.zelda
  [ "$status" -ne 0 ]
  # Steam cannot evaluate nix, so this has to be an instruction, not an attempt.
  [[ "$stderr" == *"terminal"* ]]
  [[ "$stderr" == *"gotg install usa.zelda"* ]]
}

@test "play downloads a game that is missing before launching it" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  [ ! -e "$GOTG_GAMES_DIR/n64/usa.zelda.z64" ]

  gotg play usa.zelda
  [ "$status" -eq 0 ]
  [ -f "$GOTG_GAMES_DIR/n64/usa.zelda.z64" ]
  [[ "$output" == *"launched with:"* ]]
}

@test "titles with shell and sed metacharacters produce a sound launcher" {
  # 45 games in the real library have "&" in the title, which sed expands to the
  # matched text; "|" is the delimiter and would abort generation outright.
  mkdir -p "$SERVER_ROOT/Games/n64"
  printf 'rom' > "$SERVER_ROOT/Games/n64/usa.cnc.z64"
  local sha size
  sha="$(sha256sum "$SERVER_ROOT/Games/n64/usa.cnc.z64" | cut -d' ' -f1)"
  size="$(stat -c '%s' "$SERVER_ROOT/Games/n64/usa.cnc.z64")"
  add_manifest_entry n64 "/Games/n64/usa.cnc.z64" file "$size" "$sha" \
    'Command & Conquer | $(touch /tmp/pwned) `id` \1'

  gotg refresh
  gotg install usa.cnc
  [ "$status" -eq 0 ]

  local launcher="$GOTG_GAMES_DIR/n64/play-usa.cnc.sh"
  # The title survives verbatim rather than being mangled into "@TITLE@".
  grep -q 'Command & Conquer' "$launcher"
  ! grep -q '@TITLE@' "$launcher"
  # And the launcher is still valid, single-purpose bash.
  bash -n "$launcher"
  [ ! -e /tmp/pwned ]
  run bash "$launcher"
  [ ! -e /tmp/pwned ]
}

@test "a title containing a newline cannot break out of its comment line" {
  mkdir -p "$SERVER_ROOT/Games/n64"
  printf 'rom' > "$SERVER_ROOT/Games/n64/usa.nl.z64"
  local sha size
  sha="$(sha256sum "$SERVER_ROOT/Games/n64/usa.nl.z64" | cut -d' ' -f1)"
  size="$(stat -c '%s' "$SERVER_ROOT/Games/n64/usa.nl.z64")"
  add_manifest_entry n64 "/Games/n64/usa.nl.z64" file "$size" "$sha" \
    "$(printf 'Game\ntouch /tmp/pwned-nl')"

  gotg refresh
  gotg install usa.nl
  [ "$status" -eq 0 ]
  bash -n "$GOTG_GAMES_DIR/n64/play-usa.nl.sh"
  run bash "$GOTG_GAMES_DIR/n64/play-usa.nl.sh"
  [ ! -e /tmp/pwned-nl ]
}
