#!/usr/bin/env bats
# The generated Steam launcher. Every line in it is load-bearing under Steam, so
# these assert the workarounds are present rather than just that a file appeared.

bats_require_minimum_version 1.5.0

load helper

setup() {
  setup_env
  start_server
  write_config

  # A stand-in for client/env. Only the file names decide which environment a
  # game wants, so this is all the CLI reads; the built root is faked alongside
  # it, which keeps every test here clear of nix.
  export GOTG_ENV_DIR="$TEST_TMP/env"
  mkdir -p "$GOTG_ENV_DIR"
  : >"$GOTG_ENV_DIR/n64.nix"
  fake_env env-n64

  mkdir -p "$TEST_TMP/data"
  echo '{}' >"$TEST_TMP/data/overrides.json"
  export GOTG_DATA="$TEST_TMP/data"
}

teardown() {
  stop_server
}

@test "install writes an executable launcher next to the game" {
  add_game n64 "usa.zelda.z64" "rom" "Zelda"
  gotg refresh
  gotg install usa.zelda
  [ "$status" -eq 0 ]

  local launcher="$GOTG_GAMES_DIR/n64/play-usa.zelda.sh"
  [ -x "$launcher" ]
  [[ "$stderr" == *"$launcher"* ]]
}

@test "the launcher carries every Steam workaround" {
  add_game n64 "usa.zelda.z64" "rom" "Zelda"
  gotg refresh
  gotg install usa.zelda
  local launcher="$GOTG_GAMES_DIR/n64/play-usa.zelda.sh"

  # Steam gives a minimal PATH, so nix has to be findable.
  grep -q 'run/current-system/sw/bin' "$launcher"
  # Steam suppresses SDL controller detection for non-Steam apps.
  grep -q 'SDL_JOYSTICK_HIDAPI=0' "$launcher"
  grep -q 'unset SDL_GAMECONTROLLER_IGNORE_DEVICES' "$launcher"
  # The overlay's LD_PRELOAD breaks nix wrapper scripts.
  grep -q 'unset LD_PRELOAD' "$launcher"
  # Steam swallows output, so each launch has to leave a log.
  grep -q 'gotg/logs/usa.zelda.log' "$launcher"
  # gotg is called by absolute path; PATH lookup is unreliable under Steam.
  grep -q 'state}/gotg/app/bin/gotg' "$launcher"
  grep -q 'play "usa.zelda"' "$launcher"
}

@test "the launcher passes a platform-qualified id when one is needed" {
  add_game n64 "usa.bugs_life.zip" "n64"
  add_game snes "usa.bugs_life.zip" "snes"
  gotg refresh
  gotg install n64/usa.bugs_life
  [ "$status" -eq 0 ]

  grep -q 'play "n64/usa.bugs_life"' "$GOTG_GAMES_DIR/n64/play-usa.bugs_life.sh"
}

@test "a hand-written launcher is backed up, never overwritten" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  mkdir -p "$GOTG_GAMES_DIR/n64"
  local launcher="$GOTG_GAMES_DIR/n64/play-usa.zelda.sh"
  echo '#!/bin/bash: my careful hand-tuned script' >"$launcher"

  gotg install usa.zelda
  [ "$status" -eq 0 ]
  [ -f "$launcher.bak" ]
  grep -q 'hand-tuned' "$launcher.bak"
  grep -q 'generated by gotg' "$launcher"
}

@test "regenerating does not pile up backups of our own launchers" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  gotg install usa.zelda
  gotg install usa.zelda
  [ "$status" -eq 0 ]
  [ ! -e "$GOTG_GAMES_DIR/n64/play-usa.zelda.sh.bak" ]
}

@test "play launches the platform environment with the game as its argument" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  gotg download usa.zelda
  gotg play usa.zelda
  [ "$status" -eq 0 ]
  [[ "$output" == *"env-n64 launched with: $GOTG_GAMES_DIR/n64/usa.zelda.z64"* ]]
}

@test "a game with its own environment file gets that one, not the platform's" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  gotg download usa.zelda
  mkdir -p "$GOTG_ENV_DIR/games/n64"
  : >"$GOTG_ENV_DIR/games/n64/usa.zelda.nix"
  # The dot in an id is an attribute path separator in a flake reference.
  fake_env env-n64-usa_zelda

  gotg play usa.zelda
  [ "$status" -eq 0 ]
  [[ "$output" == *"env-n64-usa_zelda launched with:"* ]]
}

@test "play builds a missing environment from the flake" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  gotg download usa.zelda
  rm -rf "$GOTG_ROOTS_DIR/env-n64"
  stub_nix

  gotg play usa.zelda
  [ "$status" -eq 0 ]
  grep -q "build $GOTG_FLAKE#env-n64 -o $GOTG_ROOTS_DIR/env-n64" "$NIX_LOG"
  [[ "$output" == *"launched with: $GOTG_GAMES_DIR/n64/usa.zelda.z64"* ]]
}

@test "the environment is built before the download, not after it" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  rm -rf "$GOTG_ROOTS_DIR/env-n64"
  stub_nix fail

  gotg play usa.zelda
  [ "$status" -ne 0 ]
  # Nothing was fetched: a missing emulator is worth failing on before a transfer
  # that can run to tens of gigabytes.
  [ ! -e "$GOTG_GAMES_DIR/n64/usa.zelda.z64" ]
}

@test "a failed build says how to run it somewhere it can be read" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  rm -rf "$GOTG_ROOTS_DIR/env-n64"
  stub_nix fail

  gotg play usa.zelda
  [ "$status" -ne 0 ]
  [[ "$stderr" == *"terminal"* ]]
  [[ "$stderr" == *"nix build $GOTG_FLAKE#env-n64"* ]]
  # Under Steam the only trace of a launch is the log the shortcut redirects to.
  [[ "$stderr" == *"$GOTG_LOG_DIR"* ]]
}

@test "a platform with no environment says where to add one" {
  add_game snes "usa.mario.sfc" "rom"
  gotg refresh

  gotg play usa.mario
  [ "$status" -ne 0 ]
  [[ "$stderr" == *"client/env/snes.nix"* ]]
}

@test "play downloads a game that is missing before launching it" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  [ ! -e "$GOTG_GAMES_DIR/n64/usa.zelda.z64" ]

  gotg play usa.zelda
  [ "$status" -eq 0 ]
  [ -f "$GOTG_GAMES_DIR/n64/usa.zelda.z64" ]
  [[ "$output" == *"launched with:"* ]]
}

@test "titles with shell and sed metacharacters produce a sound launcher" {
  # 45 games in the real library have "&" in the title, which sed expands to the
  # matched text; "|" is the delimiter and would abort generation outright.
  mkdir -p "$SERVER_ROOT/Games/n64"
  printf 'rom' > "$SERVER_ROOT/Games/n64/usa.cnc.z64"
  local sha size
  sha="$(sha256sum "$SERVER_ROOT/Games/n64/usa.cnc.z64" | cut -d' ' -f1)"
  size="$(stat -c '%s' "$SERVER_ROOT/Games/n64/usa.cnc.z64")"
  add_manifest_entry n64 "/Games/n64/usa.cnc.z64" file "$size" "$sha" \
    'Command & Conquer | $(touch /tmp/pwned) `id` \1'

  gotg refresh
  gotg install usa.cnc
  [ "$status" -eq 0 ]

  local launcher="$GOTG_GAMES_DIR/n64/play-usa.cnc.sh"
  # The title survives verbatim rather than being mangled into "@TITLE@".
  grep -q 'Command & Conquer' "$launcher"
  ! grep -q '@TITLE@' "$launcher"
  # And the launcher is still valid, single-purpose bash.
  bash -n "$launcher"
  [ ! -e /tmp/pwned ]
  run bash "$launcher"
  [ ! -e /tmp/pwned ]
}

@test "a title containing a newline cannot break out of its comment line" {
  mkdir -p "$SERVER_ROOT/Games/n64"
  printf 'rom' > "$SERVER_ROOT/Games/n64/usa.nl.z64"
  local sha size
  sha="$(sha256sum "$SERVER_ROOT/Games/n64/usa.nl.z64" | cut -d' ' -f1)"
  size="$(stat -c '%s' "$SERVER_ROOT/Games/n64/usa.nl.z64")"
  add_manifest_entry n64 "/Games/n64/usa.nl.z64" file "$size" "$sha" \
    "$(printf 'Game\ntouch /tmp/pwned-nl')"

  gotg refresh
  gotg install usa.nl
  [ "$status" -eq 0 ]
  bash -n "$GOTG_GAMES_DIR/n64/play-usa.nl.sh"
  run bash "$GOTG_GAMES_DIR/n64/play-usa.nl.sh"
  [ ! -e /tmp/pwned-nl ]
}
