#!/usr/bin/env bash
# @TITLE@ — generated by gotg, do not edit. Regenerate with: gotg install @REF@
#
# Add this file to Steam as a non-Steam game. It downloads the game if it is not
# here yet, then launches it.
#
# Everything below is Steam-proofing; the actual work happens in `gotg play`.
set -euo pipefail

# Steam launches shortcuts with a minimal PATH, so make nix findable.
export PATH="/run/current-system/sw/bin:$HOME/.nix-profile/bin:/nix/var/nix/profiles/default/bin:$PATH"

# Controller fix. Steam injects env vars that suppress SDL controller detection
# for non-Steam apps (it expects them to use the Steam Input API, which these
# emulators do not). Undo them so SDL sees the Steam Input virtual gamepad.
export SDL_JOYSTICK_HIDAPI=0
export SDL_JOYSTICK_DISABLE_UDEV=0
unset SDL_GAMECONTROLLER_IGNORE_DEVICES

# Steam LD_PRELOADs gameoverlayrenderer.so into everything this script spawns.
# nix-wrapped binaries are bash wrappers, and the overlay's libGL dependency
# cannot be resolved from nix bash's library paths, so they die on startup with
# "cannot open shared object file". Dropping the preload loses only the overlay.
unset LD_PRELOAD

# Steam swallows stdout and stderr, so keep a log of the last launch.
LOG="${XDG_STATE_HOME:-$HOME/.local/state}/gotg/logs/@ID@.log"
mkdir -p "$(dirname "$LOG")"
exec >"$LOG" 2>&1
echo "launch: $(date) args: $*"

# Call gotg by absolute path: PATH lookup is unreliable under Steam, and this
# symlink is a nix GC root so the store path it points at cannot be collected.
GOTG="${XDG_STATE_HOME:-$HOME/.local/state}/gotg/app/bin/gotg"
if [[ ! -x "$GOTG" ]]; then
  GOTG="$(command -v gotg 2>/dev/null || true)"
fi
if [[ -z "$GOTG" || ! -x "$GOTG" ]]; then
  echo "error: gotg not found. From a terminal, run:"
  echo "  nix build @FLAKE@#gotg -o \"${XDG_STATE_HOME:-$HOME/.local/state}/gotg/app\""
  exit 1
fi

exec "$GOTG" play "@REF@" "$@"
