#!/usr/bin/env bats
# The generated Steam launcher. Every line in it is load-bearing under Steam, so
# these assert the workarounds are present rather than just that a file appeared.

bats_require_minimum_version 1.5.0

load helper

setup() {
  setup_env
  start_saves_service
  write_api_config

  # A stand-in for client/env. Only the file names decide which environment a
  # game wants, so this is all the CLI reads; the built root is faked alongside
  # it, which keeps every test here clear of nix.
  export GOTG_ENV_DIR="$TEST_TMP/env"
  mkdir -p "$GOTG_ENV_DIR"
  : >"$GOTG_ENV_DIR/n64.nix"
  fake_env env-n64

  mkdir -p "$TEST_TMP/data"
  echo '{}' >"$TEST_TMP/data/overrides.json"
  export GOTG_DATA="$TEST_TMP/data"
}

teardown() {
  stop_saves_service
}

@test "install writes an executable launcher next to the game" {
  add_game n64 "usa.zelda.z64" "rom" "Zelda"
  gotg refresh
  gotg install usa.zelda
  [ "$status" -eq 0 ]

  local launcher="$GOTG_GAMES_DIR/n64/play-usa.zelda.sh"
  [ -x "$launcher" ]
  [[ "$stderr" == *"$launcher"* ]]
}

@test "the launcher carries every Steam workaround" {
  add_game n64 "usa.zelda.z64" "rom" "Zelda"
  gotg refresh
  gotg install usa.zelda
  local launcher="$GOTG_GAMES_DIR/n64/play-usa.zelda.sh"

  # Steam gives a minimal PATH, so nix has to be findable.
  grep -q 'run/current-system/sw/bin' "$launcher"
  # Steam suppresses SDL controller detection for non-Steam apps.
  grep -q 'SDL_JOYSTICK_HIDAPI=0' "$launcher"
  grep -q 'unset SDL_GAMECONTROLLER_IGNORE_DEVICES' "$launcher"
  # The overlay's LD_PRELOAD breaks nix wrapper scripts.
  grep -q 'unset LD_PRELOAD' "$launcher"
  # Steam swallows output, so each launch has to leave a log.
  grep -q 'gotg/logs/usa.zelda.log' "$launcher"
  # gotg is called by absolute path; PATH lookup is unreliable under Steam.
  grep -q 'state}/gotg/app/bin/gotg' "$launcher"
  grep -q 'play "usa.zelda"' "$launcher"
}

@test "the launcher passes a platform-qualified id when one is needed" {
  add_game n64 "usa.bugs_life.zip" "n64"
  add_game snes "usa.bugs_life.zip" "snes"
  gotg refresh
  gotg install n64/usa.bugs_life
  [ "$status" -eq 0 ]

  grep -q 'play "n64/usa.bugs_life"' "$GOTG_GAMES_DIR/n64/play-usa.bugs_life.sh"
}

@test "a hand-written launcher is backed up, never overwritten" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  mkdir -p "$GOTG_GAMES_DIR/n64"
  local launcher="$GOTG_GAMES_DIR/n64/play-usa.zelda.sh"
  echo '#!/bin/bash: my careful hand-tuned script' >"$launcher"

  gotg install usa.zelda
  [ "$status" -eq 0 ]
  [ -f "$launcher.bak" ]
  grep -q 'hand-tuned' "$launcher.bak"
  grep -q 'generated by gotg' "$launcher"
}

@test "regenerating does not pile up backups of our own launchers" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  gotg install usa.zelda
  gotg install usa.zelda
  [ "$status" -eq 0 ]
  [ ! -e "$GOTG_GAMES_DIR/n64/play-usa.zelda.sh.bak" ]
}

@test "play launches the platform environment with the game as its argument" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  gotg download usa.zelda
  gotg play usa.zelda
  [ "$status" -eq 0 ]
  [[ "$output" == *"env-n64 launched with: $GOTG_GAMES_DIR/n64/usa.zelda.z64"* ]]
}

@test "a game with its own environment file gets that one, not the platform's" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  gotg download usa.zelda
  mkdir -p "$GOTG_ENV_DIR/games/n64"
  : >"$GOTG_ENV_DIR/games/n64/usa.zelda.nix"
  # The dot in an id is an attribute path separator in a flake reference.
  fake_env env-n64-usa_zelda

  gotg play usa.zelda
  [ "$status" -eq 0 ]
  [[ "$output" == *"env-n64-usa_zelda launched with:"* ]]
}

@test "a decomp game launches its own port with the unzipped rom" {
  # The shape the Zelda ports need: a No-Intro zip unpacked to a bare .z64, a
  # glob to pick that file out of the directory it became, and an environment
  # belonging to the game rather than the platform.
  mkdir -p "$TEST_TMP/mkzip" "$SERVICE_LIBRARY_DIR/n64"
  printf 'rom bytes' >"$TEST_TMP/mkzip/Zelda (USA).z64"
  (cd "$TEST_TMP/mkzip" && zip -q "$SERVICE_LIBRARY_DIR/n64/usa.zelda.zip" "Zelda (USA).z64")
  local sha size
  sha="$(sha256sum "$SERVICE_LIBRARY_DIR/n64/usa.zelda.zip" | cut -d' ' -f1)"
  size="$(stat -c '%s' "$SERVICE_LIBRARY_DIR/n64/usa.zelda.zip")"
  add_manifest_entry n64 "/Games/n64/usa.zelda.zip" file "$size" "$sha" "Zelda"
  jq -n '{"n64/usa.zelda": {unzip: true, target: "*.z64"}}' >"$TEST_TMP/data/overrides.json"

  mkdir -p "$GOTG_ENV_DIR/games/n64"
  : >"$GOTG_ENV_DIR/games/n64/usa.zelda.nix"
  fake_env env-n64-usa_zelda
  stub_unzip_recipe env-n64-usa_zelda

  gotg refresh
  gotg play usa.zelda
  [ "$status" -eq 0 ]
  # The bare ROM inside the unpacked directory, not the directory or the zip.
  [[ "$output" == *"env-n64-usa_zelda launched with: $GOTG_GAMES_DIR/n64/usa.zelda/Zelda (USA).z64"* ]]
}

@test "a zip with filler and a nested rom still resolves the target by glob" {
  mkdir -p "$TEST_TMP/mkzip/Zelda (USA)" "$SERVICE_LIBRARY_DIR/n64"
  printf 'rom bytes' >"$TEST_TMP/mkzip/Zelda (USA)/Zelda (USA).z64"
  printf 'read me' >"$TEST_TMP/mkzip/readme.txt"
  (cd "$TEST_TMP/mkzip" && zip -qr "$TEST_TMP/usa.zelda.zip" "Zelda (USA)" readme.txt)
  add_binary_game n64 "$TEST_TMP/usa.zelda.zip" "usa.zelda.zip" "Zelda"
  jq -n '{"n64/usa.zelda": {unzip: true, target: "*.z64"}}' >"$TEST_TMP/data/overrides.json"

  mkdir -p "$GOTG_ENV_DIR/games/n64"
  : >"$GOTG_ENV_DIR/games/n64/usa.zelda.nix"
  fake_env env-n64-usa_zelda
  stub_unzip_recipe env-n64-usa_zelda

  gotg refresh
  gotg play usa.zelda
  [ "$status" -eq 0 ]
  [[ "$output" == *"env-n64-usa_zelda launched with: $GOTG_GAMES_DIR/n64/usa.zelda/Zelda (USA)/Zelda (USA).z64"* ]]
}

@test "every override in the shipped data is keyed by a well-formed id" {
  local shipped
  shipped="$(dirname "$GOTG_BIN")/../share/gotg/data/overrides.json"
  [ -f "$shipped" ]

  # A typo in one of these keys fails silently — the override simply never
  # matches the game it was written for, and the game launches wrong.
  run jq -r 'keys[] | select(startswith("_") | not)' "$shipped"
  [ "$status" -eq 0 ]
  [ -n "$output" ]

  local key
  while read -r key; do
    [[ "$key" =~ ^([a-z0-9][a-z0-9_-]*/)?[a-z]{3,5}\.[a-z0-9][a-z0-9_]*$ ]] || {
      echo "malformed override key: $key" >&2
      return 1
    }
  done <<<"$output"
}

@test "play builds a missing environment from the flake" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  gotg download usa.zelda
  rm -rf "$GOTG_ROOTS_DIR/env-n64"
  stub_nix

  gotg play usa.zelda
  [ "$status" -eq 0 ]
  grep -q "build $GOTG_FLAKE#env-n64 -o $GOTG_ROOTS_DIR/env-n64" "$NIX_LOG"
  [[ "$output" == *"launched with: $GOTG_GAMES_DIR/n64/usa.zelda.z64"* ]]
}

@test "the environment is built before the download, not after it" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  rm -rf "$GOTG_ROOTS_DIR/env-n64"
  stub_nix fail

  gotg play usa.zelda
  [ "$status" -ne 0 ]
  # Nothing was fetched: a missing emulator is worth failing on before a transfer
  # that can run to tens of gigabytes.
  [ ! -e "$GOTG_GAMES_DIR/n64/usa.zelda.z64" ]
}

@test "a failed build says how to run it somewhere it can be read" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  rm -rf "$GOTG_ROOTS_DIR/env-n64"
  stub_nix fail

  gotg play usa.zelda
  [ "$status" -ne 0 ]
  [[ "$stderr" == *"terminal"* ]]
  [[ "$stderr" == *"nix build $GOTG_FLAKE#env-n64"* ]]
  # Under Steam the only trace of a launch is the log the shortcut redirects to.
  [[ "$stderr" == *"$GOTG_LOG_DIR"* ]]
}

@test "a platform with no environment says where to add one" {
  add_game snes "usa.mario.sfc" "rom"
  gotg refresh

  gotg play usa.mario
  [ "$status" -ne 0 ]
  [[ "$stderr" == *"src/client/env/snes.nix"* ]]
}

@test "play downloads a game that is missing before launching it" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  [ ! -e "$GOTG_GAMES_DIR/n64/usa.zelda.z64" ]

  gotg play usa.zelda
  [ "$status" -eq 0 ]
  [ -f "$GOTG_GAMES_DIR/n64/usa.zelda.z64" ]
  [[ "$output" == *"launched with:"* ]]
}

@test "titles with shell and sed metacharacters produce a sound launcher" {
  # 45 games in the real library have "&" in the title, which sed expands to the
  # matched text; "|" is the delimiter and would abort generation outright.
  mkdir -p "$SERVICE_LIBRARY_DIR/n64"
  printf 'rom' > "$SERVICE_LIBRARY_DIR/n64/usa.cnc.z64"
  local sha size
  sha="$(sha256sum "$SERVICE_LIBRARY_DIR/n64/usa.cnc.z64" | cut -d' ' -f1)"
  size="$(stat -c '%s' "$SERVICE_LIBRARY_DIR/n64/usa.cnc.z64")"
  add_manifest_entry n64 "/Games/n64/usa.cnc.z64" file "$size" "$sha" \
    'Command & Conquer | $(touch /tmp/pwned) `id` \1'

  gotg refresh
  gotg install usa.cnc
  [ "$status" -eq 0 ]

  local launcher="$GOTG_GAMES_DIR/n64/play-usa.cnc.sh"
  # The title survives verbatim rather than being mangled into "@TITLE@".
  grep -q 'Command & Conquer' "$launcher"
  ! grep -q '@TITLE@' "$launcher"
  # And the launcher is still valid, single-purpose bash.
  bash -n "$launcher"
  [ ! -e /tmp/pwned ]
  run bash "$launcher"
  [ ! -e /tmp/pwned ]
}

@test "a title containing a newline cannot break out of its comment line" {
  # The service refuses non-printable titles outright, so the hostile row can
  # only arrive through a poisoned cache — which is exactly what the launcher
  # writer must still survive.
  mkdir -p "$GOTG_GAMES_DIR/n64" "$GOTG_STATE_DIR"
  printf 'rom' >"$GOTG_GAMES_DIR/n64/usa.nl.z64"
  jq -n --arg t "$(printf 'Game\ntouch /tmp/pwned-nl')" \
    '{version: 2, games: [{id: "usa.nl", platform: "n64", handler: "single_file",
      title: $t, files: [{name: "usa.nl.z64", size_bytes: 3, sha256: null}]}]}' \
    >"$GOTG_CACHE_FILE"
  fake_env env-n64

  gotg install usa.nl
  [ "$status" -eq 0 ]
  bash -n "$GOTG_GAMES_DIR/n64/play-usa.nl.sh"
  run bash "$GOTG_GAMES_DIR/n64/play-usa.nl.sh"
  [ ! -e /tmp/pwned-nl ]
}

@test "a named variant selects an environment of its own" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  gotg download usa.zelda
  mkdir -p "$GOTG_ENV_DIR/games/n64"
  : >"$GOTG_ENV_DIR/games/n64/usa.zelda.hd.nix"
  fake_env env-n64-usa_zelda-hd

  gotg play usa.zelda hd
  [ "$status" -eq 0 ]
  [[ "$output" == *"env-n64-usa_zelda-hd launched with:"* ]]
}

@test "an unknown variant fails and says which exist" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  mkdir -p "$GOTG_ENV_DIR/games/n64"
  : >"$GOTG_ENV_DIR/games/n64/usa.zelda.hd.nix"

  gotg play usa.zelda randomtypo
  [ "$status" -ne 0 ]
  # A typo must not be passed to the emulator, where it would look like the
  # variant silently not working.
  [[ "$stderr" == *"no 'randomtypo' variant"* ]]
  [[ "$stderr" == *"Available: hd"* ]]
}

@test "an emulator argument is not mistaken for a variant" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  gotg download usa.zelda

  gotg play usa.zelda --fullscreen
  [ "$status" -eq 0 ]
  # Straight through to the platform environment, with the flag passed on.
  [[ "$output" == *"env-n64 launched with:"* ]]
  [[ "$output" == *"--fullscreen"* ]]
}

@test "no checkout anywhere means environments build from the repo itself" {
  load_client_libs
  local out
  out="$(HOME="$TEST_TMP/nohome" GOTG_FLAKE="" gotg_flake)"
  [[ "$out" == "github:dscrawford/GamesOnTheGo"* ]]
}

@test "the default flake is the one form nix can authenticate by itself" {
  # Not git+ssh (needs a key on the repo) and not git+https (shells out to
  # git, which asks for a username): nix's access-tokens setting applies to
  # github: refs only, and a read-only token is the whole point of the
  # default. Measured, not assumed — git+https with a token set fails with
  # "could not read Username for 'https://github.com'".
  load_client_libs
  local out
  out="$(HOME="$TEST_TMP/nohome" GOTG_FLAKE="" gotg_flake)"
  [[ "$out" == github:* ]]
  [[ "$out" != *ssh* ]]
  [[ "$out" != git+https* ]]
}

@test "a checkout in the usual place still wins over the network" {
  load_client_libs
  mkdir -p "$TEST_TMP/home/Documents/GOTG"
  : >"$TEST_TMP/home/Documents/GOTG/flake.nix"
  local out
  out="$(HOME="$TEST_TMP/home" GOTG_FLAKE="" gotg_flake)"
  [ "$out" = "$TEST_TMP/home/Documents/GOTG" ]
}

@test "a url flake goes to nix without a local flake.nix check" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  gotg download usa.zelda
  rm -rf "$GOTG_ROOTS_DIR/env-n64"
  stub_nix
  export GOTG_FLAKE="git+ssh://git@example.com/repo?shallow=1"
  gotg play usa.zelda
  [ "$status" -eq 0 ]
  grep -q "build git+ssh://git@example.com/repo?shallow=1#env-n64" "$NIX_LOG"
}

@test "sync with a url flake refreshes rather than dying on a missing checkout" {
  stub_nix
  export GOTG_FLAKE="git+ssh://git@example.com/repo?shallow=1"
  gotg sync
  [ "$status" -eq 0 ]
  grep -q -- "build git+ssh://git@example.com/repo?shallow=1#gotg .* --refresh" "$NIX_LOG"
}

@test "sync marks each environment on one line" {
  stub_nix
  fake_env env-n64
  fake_env env-snes
  gotg sync
  [ "$status" -eq 0 ]
  [[ "$stderr" == *"● gotg"* ]]
  [[ "$stderr" == *"● env-n64"*"same"* ]]
  [[ "$stderr" == *"● env-snes"*"same"* ]]
  # No prose per environment: the line is the report.
  [[ "$stderr" != *"rebuilding env-n64"* ]]
  [[ "$stderr" != *"building env-n64 from"* ]]
}

@test "an environment that fails to build is marked, and the others still sync" {
  stub_nix fail-env
  fake_env env-n64
  fake_env env-broken
  gotg sync
  [ "$status" -ne 0 ]
  [[ "$stderr" == *"● env-broken"*"sync-env-broken.log"* ]]
  [[ "$stderr" == *"● env-n64"*"same"* ]]
  [[ "$stderr" == *"1 environment(s) did not build"* ]]
  grep -q "build .*#env-n64" "$NIX_LOG"
}

@test "a root that is not an environment is marked and skipped" {
  stub_nix
  fake_env env-n64
  mkdir -p "$GOTG_ROOTS_DIR/ares"
  gotg sync
  [ "$status" -eq 0 ]
  [[ "$stderr" == *"● ares"*"not an environment name"* ]]
  [[ "$stderr" == *"● env-n64"* ]]
}

# --- sync skips a flake that has not changed ---

commit_flake() {
  git -C "$GOTG_FLAKE" init -q 2>/dev/null || true
  git -C "$GOTG_FLAKE" -c user.name=t -c user.email=t@t add -A
  git -C "$GOTG_FLAKE" -c user.name=t -c user.email=t@t commit -q -m "${1:-flake}" --allow-empty
}

@test "a second sync on the same commit builds nothing" {
  stub_nix
  fake_env env-n64
  commit_flake
  gotg sync
  [ "$status" -eq 0 ]
  local builds
  builds="$(grep -c "^build " "$NIX_LOG")"
  [ "$builds" -eq 2 ]

  gotg sync
  [ "$status" -eq 0 ]
  [[ "$stderr" == *"nothing changed since"* ]]
  [[ "$stderr" == *"● env-n64"*"same"* ]]
  [ "$(grep -c "^build " "$NIX_LOG")" -eq 2 ]

  # A new commit, or a dirty checkout, or --force: built again.
  commit_flake again
  gotg sync
  [ "$(grep -c "^build " "$NIX_LOG")" -eq 4 ]
  gotg sync --force
  [ "$(grep -c "^build " "$NIX_LOG")" -eq 6 ]
  echo edit >>"$GOTG_FLAKE/flake.nix"
  gotg sync
  [ "$(grep -c "^build " "$NIX_LOG")" -eq 8 ]
}

@test "a sync that failed does not stamp the flake as done" {
  stub_nix fail-env
  fake_env env-broken
  commit_flake
  gotg sync
  [ "$status" -ne 0 ]
  [ ! -f "$GOTG_STATE_DIR/sync.rev" ]
  gotg sync
  [ "$status" -ne 0 ]
  [[ "$stderr" != *"nothing changed"* ]]
}

@test "install points at the command, not at Steam's file picker" {
  add_game n64 "usa.zelda.z64" "rom" "Zelda"
  gotg refresh
  gotg install usa.zelda
  [ "$status" -eq 0 ]
  [[ "$stderr" == *"gotg steam add usa.zelda"* ]]
  [[ "$stderr" != *"Add a Non-Steam Game"* ]]
}


# --- the progress dialog, when there is a display and no terminal -------------
#
# Under Steam a build fronts itself with a zenity dialog. On a Deck zenity
# refused GOTG's own arguments -- "This option is not available" -- because
# the locale was C and the text had an ellipsis in it; and the client read
# the dialog vanishing as a cancellation and killed every build.

fake_zenity() {
  local mode="${1:-refuse}"
  export ZENITY_LOG="$TEST_TMP/zenity.log"
  export GOTG_ZENITY="$TEST_TMP/bin/zenity"
  mkdir -p "$TEST_TMP/bin"
  {
    printf '#!%s\n' "$(command -v bash)"
    printf 'printf "LC_ALL=%%s args=%%s\\n" "$LC_ALL" "$*" >>"$ZENITY_LOG"\n'
    if [[ "$mode" == refuse ]]; then
      printf 'echo "This option is not available. Please see --help for all possible usages." >&2\nexit 255\n'
    else
      printf 'cat >/dev/null\nexit 0\n'
    fi
  } >"$GOTG_ZENITY"
  chmod +x "$GOTG_ZENITY"
  # A display and no terminal: the dialog path. bats gives us the no-terminal.
  export DISPLAY=:0
  unset GOTG_NO_DIALOG
}

@test "a dialog that cannot start does not stop the build" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  gotg download usa.zelda
  rm -rf "$GOTG_ROOTS_DIR/env-n64"
  stub_nix
  fake_zenity refuse

  gotg play usa.zelda
  [ "$status" -eq 0 ]
  grep -q "build $GOTG_FLAKE#env-n64" "$NIX_LOG"
  [[ "$stderr" == *"progress dialog could not start"* ]]
  [[ "$stderr" != *"build stopped"* ]]
}

@test "the dialog runs in a locale that can read an ellipsis or an accent" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  gotg download usa.zelda
  rm -rf "$GOTG_ROOTS_DIR/env-n64"
  stub_nix
  fake_zenity ok

  LC_ALL=C gotg play usa.zelda
  [ "$status" -eq 0 ]
  grep -q "^LC_ALL=C.UTF-8 args=--progress" "$ZENITY_LOG"
}

@test "a download whose dialog cannot start still downloads" {
  add_game n64 "usa.zelda.z64" "rom-content"
  gotg refresh
  fake_zenity refuse

  gotg download usa.zelda
  [ "$status" -eq 0 ]
  [ "$(cat "$GOTG_GAMES_DIR/n64/usa.zelda.z64")" = rom-content ]
  [[ "$stderr" == *"progress dialog could not start"* ]]
}

@test "the dialog's scratch directory is only ever one mktemp made" {
  # The one `rm -rf` on this path must never see a name from anywhere else.
  load_client_libs
  d="$(dialog_dir)"
  [ -d "$d" ]
  [[ "$d" == "${TMPDIR:-/tmp}/gotg-dialog."* ]]
  dialog_dir_remove "$d"
  [ ! -e "$d" ]
  # Anything that is not such a directory is left alone, quietly.
  mkdir -p "$TEST_TMP/precious"
  touch "$TEST_TMP/precious/file"
  dialog_dir_remove "$TEST_TMP/precious"
  dialog_dir_remove ""
  dialog_dir_remove "/"
  [ -e "$TEST_TMP/precious/file" ]
}

@test "a dialog that dies later, for its own reasons, does not stop the build either" {
  # zenity 4 initialises GTK before it parses its options, so a refused
  # option surfaces well after any start-up grace. Its exit status says
  # what happened: 255 is zenity's problem, and the build goes on.
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  gotg download usa.zelda
  rm -rf "$GOTG_ROOTS_DIR/env-n64"
  stub_nix
  fake_zenity ok
  printf '#!%s\nsleep 0.8\necho "This option is not available." >&2\nexit 255\n' "$(command -v bash)" >"$GOTG_ZENITY"
  # A build still running when the dialog dies, or the branch never runs.
  sed -i 's/^exit 0$/sleep 2; exit 0/' "$GOTG_NIX"

  gotg play usa.zelda
  [ "$status" -eq 0 ]
  [[ "$stderr" == *"went away (zenity exited 255)"* ]]
  [[ "$stderr" != *"build stopped"* ]]
}

@test "closing the dialog is still a cancellation" {
  add_game n64 "usa.zelda.z64" "rom"
  gotg refresh
  gotg download usa.zelda
  rm -rf "$GOTG_ROOTS_DIR/env-n64"
  stub_nix
  fake_zenity ok
  printf '#!%s\nsleep 0.8\nexit 1\n' "$(command -v bash)" >"$GOTG_ZENITY"
  # A build that would take long enough to be cancelled.
  sed -i 's/^exit 0$/sleep 5; exit 0/' "$GOTG_NIX"

  gotg play usa.zelda
  [ "$status" -ne 0 ]
  [[ "$stderr" == *"build stopped: the progress dialog was cancelled"* ]]
}
