#!/usr/bin/env bats
# Decisions inside uninstall and the Steam art fetch, asked directly with
# stand-ins for what they would touch.

bats_require_minimum_version 1.5.0

load helper

setup() {
  setup_env
  load_client_libs
  ROOT="$TEST_TMP/games/n64"
  mkdir -p "$ROOT"
  # The catalog's answers, as plain variables.
  UNZIP=false PLACED=false
  override_field() { printf '%s' "$UNZIP"; }
  game_is_placed_file() { [[ "$PLACED" == true ]]; }
}

@test "uninstall step: a recipe's entry is the id, with or without an extension" {
  _uninstall_check_path g "$ROOT/usa.zelda" "$ROOT" usa.zelda
  _uninstall_check_path g "$ROOT/usa.zelda.z64" "$ROOT" usa.zelda
  run _uninstall_check_path g "$ROOT/other" "$ROOT" usa.zelda
  [ "$status" -ne 0 ]
  [[ "$output" == *"a recipe installs as the id"* ]]
}

@test "uninstall step: nothing outside or below the platform directory is removed" {
  run _uninstall_check_path g "$TEST_TMP/elsewhere/usa.zelda" "$ROOT" usa.zelda
  [ "$status" -ne 0 ]
  [[ "$output" == *"not inside $ROOT"* ]]
  run _uninstall_check_path g "$ROOT" "$ROOT" usa.zelda
  [[ "$output" == *"not inside"* ]]
  run _uninstall_check_path g "$ROOT/Prefixes/usa.zelda" "$ROOT" usa.zelda
  [ "$status" -ne 0 ]
  [[ "$output" == *"this is nested"* ]]
}

@test "uninstall step: an unpacked game is its id's directory, a placed file is a plain file" {
  UNZIP=true
  _uninstall_check_path g "$ROOT/usa.zelda" "$ROOT" usa.zelda
  run _uninstall_check_path g "$ROOT/usa.zelda.z64" "$ROOT" usa.zelda
  [[ "$output" == *"an unpacked game is the directory named by its id"* ]]
  UNZIP=false PLACED=true
  printf x >"$ROOT/rom.z64"
  _uninstall_check_path g "$ROOT/rom.z64" "$ROOT" usa.zelda
  ln -s "$ROOT/rom.z64" "$ROOT/link.z64"
  run _uninstall_check_path g "$ROOT/link.z64" "$ROOT" usa.zelda
  [[ "$output" == *"a single-file entry installs as a file"* ]]
}

@test "uninstall step: only launchers gotg wrote are removed; a hand-written one is kept and said so" {
  uninstall_steam_shortcut() { :; }
  printf '#!/bin/sh\n# generated by gotg\n' >"$ROOT/play-usa.zelda.sh"
  printf '#!/bin/sh\n# generated by gotg\n' >"$ROOT/play-usa.zelda-60fps.sh"
  printf '#!/bin/sh\necho mine\n' >"$ROOT/play-usa.zelda-mine.sh"
  run --separate-stderr _uninstall_launchers "$ROOT" usa.zelda
  [ "$status" -eq 0 ]
  [ ! -e "$ROOT/play-usa.zelda.sh" ] && [ ! -e "$ROOT/play-usa.zelda-60fps.sh" ]
  [ -e "$ROOT/play-usa.zelda-mine.sh" ]
  [[ "$stderr" == *"kept $ROOT/play-usa.zelda-mine.sh — not generated by gotg"* ]]
  run _uninstall_launchers "$ROOT" usa.zelda
  [ "$status" -ne 0 ]
}

@test "art step: an explicit URL beats the proxy, and no key anywhere asks to be told" {
  export GOTG_API_FILE="$TEST_TMP/api.json"
  printf '{"url":"https://p.example.com","token":"t"}' >"$GOTG_API_FILE"
  export GOTG_STEAMGRIDDB_KEY_FILE="$TEST_TMP/none.json"
  GOTG_STEAMGRIDDB_URL=http://127.0.0.1:1 _steam_art_source
  [ "${ART_BASE[*]}" = "--base-url http://127.0.0.1:1" ]
  [ "$ART_SAY_KEY" = yes ]
}

@test "art step: this machine's token goes to the proxy; otherwise its own key; otherwise nothing" {
  export GOTG_API_FILE="$TEST_TMP/api.json"
  export GOTG_STEAMGRIDDB_KEY_FILE="$TEST_TMP/key.json"
  printf '{"url":"https://p.example.com","token":"t"}' >"$GOTG_API_FILE"
  _steam_art_source
  [ "${ART_BASE[*]}" = "--base-url https://p.example.com/steamgriddb --api-key t" ]
  [ "$ART_SAY_KEY" = no ]
  rm "$GOTG_API_FILE"
  printf '{"api_key":"k"}' >"$GOTG_STEAMGRIDDB_KEY_FILE"
  _steam_art_source
  [ "${ART_BASE[*]}" = "--api-key k" ] && [ "$ART_SAY_KEY" = no ]
  rm "$GOTG_STEAMGRIDDB_KEY_FILE"
  _steam_art_source
  [ "${#ART_BASE[@]}" -eq 0 ] && [ "$ART_SAY_KEY" = yes ]
}

@test "art step: nothing downloaded and nothing kept is a warning, files are a count" {
  ART_SAY_KEY=no
  run --separate-stderr _steam_art_report '{"downloaded":[],"kept":[],"skipped":"no key","libretro":{"downloaded":[],"kept":[],"skipped":"no match"}}'
  [[ "$stderr" == *"no artwork: no key; no match"* ]]
  run --separate-stderr _steam_art_report '{"downloaded":["a","b"],"kept":[],"game":"Zelda","libretro":{"downloaded":["c"],"kept":[]}}'
  [[ "$stderr" == *"artwork: 3 file(s) for Zelda"* ]]
  [[ "$stderr" == *"1 from libretro-thumbnails"* ]]
  [[ "$stderr" != *"No SteamGridDB key"* ]]
  ART_SAY_KEY=yes
  run --separate-stderr _steam_art_report '{"wrote":"hero.png","source":"file"}'
  [[ "$stderr" == *"artwork: hero.png, from file"* ]]
  [[ "$stderr" != *"No SteamGridDB key"* ]]
  run --separate-stderr _steam_art_report '{"downloaded":["a"],"kept":[],"libretro":{"downloaded":[],"kept":[]}}'
  [[ "$stderr" == *"No SteamGridDB key"* ]]
}
