#!/usr/bin/env bats
# `gotg uninstall` — property under test: it never removes saves, settings,
# or the shared platform environment.

bats_require_minimum_version 1.5.0

load helper

setup() {
  setup_env
  start_saves_service
  write_api_config
  add_game snes world.super_metroid.sfc "rom bytes" "Super Metroid"
  gotg refresh
  mkdir -p "$GOTG_GAMES_DIR/snes"
}

teardown() { stop_saves_service; }

install_fake() {
  printf 'rom bytes' >"$GOTG_GAMES_DIR/snes/world.super_metroid.sfc"
  printf '#!/bin/sh\n# generated by gotg\n' >"$GOTG_GAMES_DIR/snes/play-world.super_metroid.sh"
}

@test "removes the game's file and its launcher" {
  install_fake
  gotg uninstall world.super_metroid
  [ "$status" -eq 0 ]
  [ ! -e "$GOTG_GAMES_DIR/snes/world.super_metroid.sfc" ]
  [ ! -e "$GOTG_GAMES_DIR/snes/play-world.super_metroid.sh" ]
  [[ "$stderr" == *"uninstalled: Super Metroid"* ]]
}

@test "a variant's launcher goes with it" {
  install_fake
  printf '#!/bin/sh\n# generated by gotg\n' >"$GOTG_GAMES_DIR/snes/play-world.super_metroid-rando.sh"
  gotg uninstall world.super_metroid
  [ ! -e "$GOTG_GAMES_DIR/snes/play-world.super_metroid-rando.sh" ]
}

@test "a launcher somebody wrote by hand is kept, and said so" {
  install_fake
  printf '#!/bin/sh\necho mine\n' >"$GOTG_GAMES_DIR/snes/play-world.super_metroid.sh"
  gotg uninstall world.super_metroid
  [ "$status" -eq 0 ]
  [ -e "$GOTG_GAMES_DIR/snes/play-world.super_metroid.sh" ]
  [[ "$stderr" == *"kept"*"not generated by gotg"* ]]
}

@test "saves and settings stay" {
  install_fake
  mkdir -p "$GOTG_STATE_DIR/env/env-snes/saves"
  printf 'progress' >"$GOTG_STATE_DIR/env/env-snes/saves/world.super_metroid.srm"
  gotg uninstall world.super_metroid
  [ -e "$GOTG_STATE_DIR/env/env-snes/saves/world.super_metroid.srm" ]
  [[ "$stderr" == *"kept: saves and settings"* ]]
}

@test "an unpacked recipe install is a directory, and goes as one" {
  publish_unzip_game usa.zelda
  gotg refresh
  mkdir -p "$GOTG_GAMES_DIR/n64/usa.zelda"
  printf 'rom' >"$GOTG_GAMES_DIR/n64/usa.zelda/Zelda (USA).z64"
  gotg uninstall usa.zelda
  [ "$status" -eq 0 ]
  [ ! -e "$GOTG_GAMES_DIR/n64/usa.zelda" ]
}

@test "a game that is not here is not an error" {
  gotg uninstall world.super_metroid
  [ "$status" -eq 0 ]
  [[ "$stderr" == *"not installed"* ]]
}

@test "a partial download is cleared too" {
  mkdir -p "$GOTG_PARTIAL_DIR/world.super_metroid"
  printf 'half' >"$GOTG_PARTIAL_DIR/world.super_metroid/world.super_metroid.sfc.part"
  gotg uninstall world.super_metroid
  [ ! -e "$GOTG_PARTIAL_DIR/world.super_metroid" ]
}

@test "the Steam shortcut goes when Steam is closed" {
  install_fake
  export GOTG_STEAM_SHORTCUTS="$TEST_TMP/shortcuts.vdf"
  gotg steam add world.super_metroid
  [ "$status" -eq 0 ]
  gotg uninstall world.super_metroid
  [ "$status" -eq 0 ]
  [[ "$stderr" == *"removed from Steam"* ]]
  gotg steam list
  [[ "$stderr" == *"no non-Steam games"* ]]
}

@test "an unknown id is an error" {
  gotg uninstall nope.nothing
  [ "$status" -ne 0 ]
}

@test "it is listed as gone afterwards" {
  install_fake
  gotg list --installed
  [[ "$output" == *"world.super_metroid"* ]]
  gotg uninstall world.super_metroid
  gotg list --installed
  [[ "$output" != *"world.super_metroid"* ]]
}

# --- what it refuses ------------------------------------------------------------

# files[0].name is the catalog's to choose and may hold slashes, so a hostile
# row can point game_installed_path at any existing tree under
# $GOTG_GAMES_DIR/<slug>/. It must never become an rm -rf target.
@test "a member name with a slash in it is refused, and the tree survives" {
  # Written straight into the cache: the service refuses such a row, and
  # the cache is what the client trusts.
  jq -n '{version: 2, games: [{id: "nes.mario64", platform: "heroic",
          handler: "single_file", title: "Super Mario 64",
          files: [{name: "Prefixes/default", size_bytes: 1, sha256: null}]}]}' \
    >"$GOTG_CACHE_FILE"
  mkdir -p "$GOTG_GAMES_DIR/heroic/Prefixes/default"
  printf 'precious' >"$GOTG_GAMES_DIR/heroic/Prefixes/default/drive_c"
  gotg uninstall nes.mario64
  [ "$status" -ne 0 ]
  [[ "$stderr" == *"refusing"* ]]
  [ -e "$GOTG_GAMES_DIR/heroic/Prefixes/default/drive_c" ]
}

@test "a single-file entry whose path is a directory is refused" {
  mkdir -p "$GOTG_GAMES_DIR/snes/world.super_metroid.sfc"
  printf 'x' >"$GOTG_GAMES_DIR/snes/world.super_metroid.sfc/inside"
  gotg uninstall world.super_metroid
  [ "$status" -ne 0 ]
  [[ "$stderr" == *"refusing"* ]]
  [ -e "$GOTG_GAMES_DIR/snes/world.super_metroid.sfc/inside" ]
}

@test "a symlink where the file should be is refused rather than followed" {
  mkdir -p "$TEST_TMP/elsewhere"
  printf 'keep' >"$TEST_TMP/elsewhere/data"
  ln -s "$TEST_TMP/elsewhere" "$GOTG_GAMES_DIR/snes/world.super_metroid.sfc"
  gotg uninstall world.super_metroid
  [ "$status" -ne 0 ]
  [ -e "$TEST_TMP/elsewhere/data" ]
}

@test "a launcher that merely mentions the marker below its header is kept" {
  install_fake
  printf '#!/bin/sh\necho hello\n# not generated by gotg, honest\n' >"$GOTG_GAMES_DIR/snes/play-world.super_metroid.sh"
  gotg uninstall world.super_metroid
  [ -e "$GOTG_GAMES_DIR/snes/play-world.super_metroid.sh" ]
}

@test "a title cannot write escape sequences into the record" {
  jq -n --arg t "$(printf 'Evil\033[2J\rTitle')" '{version: 2, games: [{id: "usa.evil",
          platform: "snes", handler: "single_file", title: $t,
          files: [{name: "usa.evil.sfc", size_bytes: 1, sha256: null}]}]}' \
    >"$GOTG_CACHE_FILE"
  printf 'rom' >"$GOTG_GAMES_DIR/snes/usa.evil.sfc"
  gotg uninstall usa.evil
  [ "$status" -eq 0 ]
  [[ "$stderr" != *$'\033'* ]]
}

@test "a platform with no environment still uninstalls cleanly" {
  add_game zzz usa.nowhere.bin "rom" "Nowhere"
  gotg refresh
  mkdir -p "$GOTG_GAMES_DIR/zzz"
  printf 'rom' >"$GOTG_GAMES_DIR/zzz/usa.nowhere.bin"
  gotg uninstall usa.nowhere
  [ "$status" -eq 0 ]
  [[ "$stderr" == *"uninstalled: Nowhere"* ]]
  [[ "$stderr" != *"error:"* ]]
}

@test "uninstall with no id says the usage line" {
  gotg uninstall
  [ "$status" -ne 0 ]
  [[ "$stderr" == *"usage: gotg uninstall"* ]]
}

@test "a poisoned cache cannot make uninstall escape via its platform" {
  mkdir -p "$TEST_TMP/VICTIM"
  printf 'precious' >"$TEST_TMP/VICTIM/important.txt"
  jq -n '{version: 2, games: [{id: "usa.evil", platform: "../../VICTIM",
          handler: "single_file", title: "Evil",
          files: [{name: "usa.evil.z64", size_bytes: 1, sha256: null}]}]}' \
    >"$GOTG_CACHE_FILE"
  gotg uninstall usa.evil
  [ "$status" -ne 0 ]
  [ -f "$TEST_TMP/VICTIM/important.txt" ]
}

# A scene_archive recipe refines a raw member into id.<ext>, which
# game_installed_path — and so uninstall — resolves by glob, not by name.
@test "a recipe's id.<ext> install is found and removed by glob" {
  mkdir -p "$SERVICE_LIBRARY_DIR/switch"
  printf 'raw-rar-bytes' >"$SERVICE_LIBRARY_DIR/switch/world.game.rar"
  local f="$SERVICE_LIBRARY_DIR/switch/world.game.rar" sha files
  sha="$(sha256sum "$f" | cut -d' ' -f1)"
  files="$(jq -n --arg p "$f" --arg sha "$sha" \
    '[{name: "world.game.rar", path: $p, size_bytes: 13, mtime: 1, sha256: $sha}]')"
  add_member_game switch world.game "A Game" scene_archive "$files"

  export GOTG_ENV_DIR="$TEST_TMP/env"
  mkdir -p "$GOTG_ENV_DIR"
  : >"$GOTG_ENV_DIR/switch.nix"
  fake_env env-switch
  local root="$GOTG_ROOTS_DIR/env-switch"
  {
    printf '#!%s\n' "$(command -v bash)"
    cat <<'SHIM'
handler="$1"; raw="$2"; dest="$3"
printf 'refined:%s' "$(cat "$raw"/*.rar)" >"$dest.xci"
SHIM
  } >"$root/bin/gotg-recipe"
  chmod +x "$root/bin/gotg-recipe"
  jq -n '{handlers: ["scene_archive"]}' >"$root/share/gotg/recipe.json"

  gotg refresh
  gotg download world.game
  [ "$status" -eq 0 ]
  [ -f "$GOTG_GAMES_DIR/switch/world.game.xci" ]

  gotg uninstall world.game
  [ "$status" -eq 0 ]
  [ ! -e "$GOTG_GAMES_DIR/switch/world.game.xci" ]
  [[ "$stderr" == *"uninstalled: A Game"* ]]
}

@test "a shortcuts file the helper cannot parse is warned about, not fatal" {
  install_fake
  export GOTG_STEAM_SHORTCUTS="$TEST_TMP/shortcuts.vdf"
  gotg steam add world.super_metroid
  [ "$status" -eq 0 ]
  printf 'not a vdf file' >"$GOTG_STEAM_SHORTCUTS"
  gotg uninstall world.super_metroid
  [ "$status" -eq 0 ]
  [[ "$stderr" == *"could not rewrite the Steam shortcuts"* ]]
  [ ! -e "$GOTG_GAMES_DIR/snes/world.super_metroid.sfc" ]
}
