#!/usr/bin/env bats
# `gotg uninstall` — the reverse of install, for the parts that are only a
# download away.
#
# The property worth holding hardest is what it does *not* remove: a game
# uninstalled to free space is one somebody expects to pick up again, so the
# saves stay, and the shared platform environment is not this command's.

bats_require_minimum_version 1.5.0

load helper

setup() {
  setup_env
  start_saves_service
  write_api_config
  add_game snes world.super_metroid.sfc "rom bytes" "Super Metroid"
  gotg refresh
  mkdir -p "$GOTG_GAMES_DIR/snes"
}

teardown() { stop_saves_service; }

install_fake() {
  printf 'rom bytes' >"$GOTG_GAMES_DIR/snes/world.super_metroid.sfc"
  printf '#!/bin/sh\n# generated by gotg\n' >"$GOTG_GAMES_DIR/snes/play-world.super_metroid.sh"
}

@test "removes the game's file and its launcher" {
  install_fake
  gotg uninstall world.super_metroid
  [ "$status" -eq 0 ]
  [ ! -e "$GOTG_GAMES_DIR/snes/world.super_metroid.sfc" ]
  [ ! -e "$GOTG_GAMES_DIR/snes/play-world.super_metroid.sh" ]
  [[ "$stderr" == *"uninstalled: Super Metroid"* ]]
}

@test "a variant's launcher goes with it" {
  install_fake
  printf '#!/bin/sh\n# generated by gotg\n' >"$GOTG_GAMES_DIR/snes/play-world.super_metroid-rando.sh"
  gotg uninstall world.super_metroid
  [ ! -e "$GOTG_GAMES_DIR/snes/play-world.super_metroid-rando.sh" ]
}

@test "a launcher somebody wrote by hand is kept, and said so" {
  install_fake
  printf '#!/bin/sh\necho mine\n' >"$GOTG_GAMES_DIR/snes/play-world.super_metroid.sh"
  gotg uninstall world.super_metroid
  [ "$status" -eq 0 ]
  [ -e "$GOTG_GAMES_DIR/snes/play-world.super_metroid.sh" ]
  [[ "$stderr" == *"kept"*"not generated by gotg"* ]]
}

@test "saves and settings stay" {
  install_fake
  mkdir -p "$GOTG_STATE_DIR/env/env-snes/saves"
  printf 'progress' >"$GOTG_STATE_DIR/env/env-snes/saves/world.super_metroid.srm"
  gotg uninstall world.super_metroid
  [ -e "$GOTG_STATE_DIR/env/env-snes/saves/world.super_metroid.srm" ]
  [[ "$stderr" == *"kept: saves and settings"* ]]
}

@test "an unpacked recipe install is a directory, and goes as one" {
  publish_unzip_game usa.zelda
  gotg refresh
  mkdir -p "$GOTG_GAMES_DIR/n64/usa.zelda"
  printf 'rom' >"$GOTG_GAMES_DIR/n64/usa.zelda/Zelda (USA).z64"
  gotg uninstall usa.zelda
  [ "$status" -eq 0 ]
  [ ! -e "$GOTG_GAMES_DIR/n64/usa.zelda" ]
}

@test "a game that is not here is not an error" {
  gotg uninstall world.super_metroid
  [ "$status" -eq 0 ]
  [[ "$stderr" == *"not installed"* ]]
}

@test "a partial download is cleared too" {
  mkdir -p "$GOTG_PARTIAL_DIR/world.super_metroid"
  printf 'half' >"$GOTG_PARTIAL_DIR/world.super_metroid/world.super_metroid.sfc.part"
  gotg uninstall world.super_metroid
  [ ! -e "$GOTG_PARTIAL_DIR/world.super_metroid" ]
}

@test "the Steam shortcut goes when Steam is closed" {
  install_fake
  export GOTG_STEAM_SHORTCUTS="$TEST_TMP/shortcuts.vdf"
  gotg steam add world.super_metroid
  [ "$status" -eq 0 ]
  gotg uninstall world.super_metroid
  [ "$status" -eq 0 ]
  [[ "$stderr" == *"removed from Steam"* ]]
  gotg steam list
  [[ "$stderr" == *"no non-Steam games"* ]]
}

@test "an unknown id is an error" {
  gotg uninstall nope.nothing
  [ "$status" -ne 0 ]
}

@test "it is listed as gone afterwards" {
  install_fake
  gotg list --installed
  [[ "$output" == *"world.super_metroid"* ]]
  gotg uninstall world.super_metroid
  gotg list --installed
  [[ "$output" != *"world.super_metroid"* ]]
}
