# shellcheck shell=bash
# uninstall — the reverse of install, for the parts that are only a download
# away: the game's files and the launchers that point at them.
#
# What it leaves alone is the point. The environment's state directory holds
# the saves and the settings, and a game removed to free space is a game
# somebody expects to pick up again; the built environment is shared with
# every other game on its platform. Neither is this command's to take.

cmd_uninstall() {
  local want="${1:-}"
  [[ -n "$want" ]] || die "usage: gotg uninstall <id>"
  # The cached catalog is enough: a game here must be removable when the
  # server is not.
  manifest_cached || manifest_ensure

  local game id platform title
  game="$(manifest_find "$want")"
  id="$(manifest_field "$game" id)"
  platform="$(manifest_field "$game" platform)"
  title="$(manifest_field "$game" title)"
  validate_id "$id"
  validate_platform "$platform"

  local removed=""
  local path
  if path="$(game_installed_path "$game")"; then
    # game_local_path builds this from fenced fields, so it is under the
    # platform directory by construction; the check is that it stays a file
    # or a directory *inside* it, never the directory itself.
    case "$path" in
      "$GOTG_GAMES_DIR/$platform"/?*) ;;
      *) die "refusing to remove $path: not inside $GOTG_GAMES_DIR/$platform" ;;
    esac
    rm -rf -- "$path"
    log "removed: $path"
    removed=1
  fi
  # A download that never finished stages under its own name.
  local partial
  partial="$(download_partial_path "$id")"
  if [[ -e "$partial" ]]; then
    rm -rf -- "$partial"
    log "removed partial download: $partial"
    removed=1
  fi

  # The plain launcher and every variant's. Only the ones this wrote: a
  # script somebody edited by hand is theirs, and is left with a warning
  # rather than deleted on the strength of its name.
  local launcher launchers=()
  for launcher in "$GOTG_GAMES_DIR/$platform/play-$id.sh" "$GOTG_GAMES_DIR/$platform/play-$id-"*.sh; do
    [[ -e "$launcher" ]] || continue
    if grep -q 'generated by gotg' "$launcher"; then
      launchers+=("$launcher")
    else
      warn "kept $launcher — not generated by gotg"
    fi
  done
  for launcher in "${launchers[@]}"; do
    uninstall_steam_shortcut "$launcher"
    rm -f -- "$launcher"
    log "removed launcher: $launcher"
    removed=1
  done

  if [[ -z "$removed" ]]; then
    log "not installed: $title ($(game_local_path "$game"))"
    return 0
  fi
  log ""
  log "uninstalled: $title"
  log "kept: saves and settings under $(env_state_dir "$(env_attr "$game")")"
}

# Take a launcher's shortcut out of Steam, when Steam will let it stick.
# Steam rewrites shortcuts.vdf on exit, so a removal made while it runs is
# undone; rather than refuse the whole uninstall over one shortcut, the files
# go and the shortcut is named as the one thing left to do.
uninstall_steam_shortcut() {
  local launcher="$1" file result
  file="$(steam_shortcuts_file 2>/dev/null)" || return 0
  [[ -f "$file" ]] || return 0
  if [[ -z "${GOTG_STEAM_SHORTCUTS:-}" ]] && pgrep -x steam >/dev/null 2>&1; then
    warn "Steam is running, so its shortcut stays. Close Steam, then: gotg steam remove $(basename "$launcher" .sh | sed 's/^play-//')"
    return 0
  fi
  result="$(steam_helper --file "$file" remove --exe "$launcher" 2>/dev/null)" || {
    warn "could not rewrite the Steam shortcuts — the entry for $launcher stays"
    return 0
  }
  [[ "$(jq -r '.action' <<<"$result")" == "removed" ]] &&
    log "removed from Steam: $(jq -r '.name' <<<"$result")"
  return 0
}
