# shellcheck shell=bash
# uninstall — removes a game's files and its launchers. Saves, settings, and
# the shared platform environment stay: a game removed to free space is one
# somebody expects to reinstall.

cmd_uninstall() {
  local want="${1:-}"
  [[ -n "$want" ]] || die "usage: gotg uninstall <id>"
  # The cached catalog is enough: a game here must be removable when the
  # server is not.
  manifest_cached || manifest_ensure

  local game id platform title
  game="$(manifest_find "$want")"
  id="$(manifest_field "$game" id)"
  platform="$(manifest_field "$game" platform)"
  # This command's stderr is the record of what was destroyed; a title is the
  # server's to choose, and one carrying \r or an escape could rewrite it.
  title="$(sanitize_title "$(manifest_field "$game" title)")"
  validate_id "$id"
  validate_platform "$platform"

  local removed=""
  local path root handler
  root="$GOTG_GAMES_DIR/$platform"
  handler="$(manifest_field "$game" handler)"
  if path="$(game_installed_path "$game")"; then
    # "Under the platform directory" is true by construction and proves
    # nothing: files[0].name is the catalog's to choose and may hold slashes,
    # so a row naming "Prefixes/default" on a platform called heroic would
    # pass a prefix check and take a Wine prefix with it. Demand the shape
    # each handler actually installs in — one entry directly under the
    # platform directory; the id's own directory for an unpacked game; a
    # plain file when the catalog named it; the id with or without an
    # extension when a recipe made it.
    case "$path" in
      "$root"/?*) ;;
      *) die "refusing to remove $path: not inside $root" ;;
    esac
    [[ "${path#"$root/"}" != */* ]] ||
      die "refusing to remove $path: a game installs directly under $root, and this is nested"
    if [[ "$(override_field "$game" unzip)" == "true" ]]; then
      [[ "$path" == "$root/$id" ]] ||
        die "refusing to remove $path: an unpacked game is the directory named by its id"
    elif [[ "$handler" == "single_file" || "$handler" == "no_intro_set" ]]; then
      [[ -f "$path" && ! -L "$path" ]] ||
        die "refusing to remove $path: a single-file entry installs as a file, and this is not one"
    else
      [[ "$path" == "$root/$id" || "$path" == "$root/$id".* ]] ||
        die "refusing to remove $path: a recipe installs as the id, with or without an extension"
    fi
    rm -rf -- "$path"
    log "removed: $path"
    removed=1
  fi
  # A download that never finished stages under its own name. validate_id
  # already made this safe; the sink is rm -rf, so say so here as well.
  local partial
  partial="$(download_partial_path "$id")"
  case "$partial" in
    "$GOTG_PARTIAL_DIR"/?*) ;;
    *) die "refusing to remove $partial: not inside $GOTG_PARTIAL_DIR" ;;
  esac
  if [[ -e "$partial" ]]; then
    rm -rf -- "$partial"
    log "removed partial download: $partial"
    removed=1
  fi

  # Only launchers this wrote (marked "generated by gotg"); a hand-edited
  # one is kept and warned about, not deleted on the strength of its name.
  # The marker is on the template's second line; matched there rather than
  # anywhere, so a hand-written script that mentions the phrase is not one.
  local launcher launchers=()
  for launcher in "$root/play-$id.sh" "$root/play-$id-"*.sh; do
    [[ -f "$launcher" ]] || continue
    if head -n 2 -- "$launcher" 2>/dev/null | grep -qsF -e 'generated by gotg'; then
      launchers+=("$launcher")
    else
      warn "kept $launcher — not generated by gotg"
    fi
  done
  for launcher in "${launchers[@]+"${launchers[@]}"}"; do
    uninstall_steam_shortcut "$launcher"
    rm -f -- "$launcher"
    log "removed launcher: $launcher"
    removed=1
  done

  if [[ -z "$removed" ]]; then
    log "not installed: $title ($(game_local_path "$game"))"
    return 0
  fi
  log ""
  log "uninstalled: $title"
  # A platform with no environment file has no state directory to name, and
  # env_attr says so by dying — which after a successful removal would read
  # as the removal having failed.
  local attr
  if attr="$(env_attr "$game" 2>/dev/null)"; then
    log "kept: saves and settings under $(env_state_dir "$attr")"
  fi
}

# Removes the launcher's Steam shortcut, when Steam will let it stick: it
# rewrites shortcuts.vdf on exit, undoing a change made while it runs, so
# rather than block the uninstall on that, the shortcut is named as what is left.
uninstall_steam_shortcut() {
  local launcher="$1" file result
  file="$(steam_shortcuts_file 2>/dev/null)" || return 0
  [[ -f "$file" ]] || return 0
  if [[ -z "${GOTG_STEAM_SHORTCUTS:-}" ]] && pgrep -x steam >/dev/null 2>&1; then
    warn "Steam is running, so its shortcut stays. Close Steam, then: gotg steam remove $(basename "$launcher" .sh | sed 's/^play-//')"
    return 0
  fi
  result="$(steam_helper --file "$file" remove --exe "$launcher" 2>/dev/null)" || {
    warn "could not rewrite the Steam shortcuts — the entry for $launcher stays"
    return 0
  }
  [[ "$(jq -r '.action' <<<"$result")" == "removed" ]] &&
    log "removed from Steam: $(jq -r '.name' <<<"$result")"
  return 0
}
