# shellcheck shell=bash
# Generating the per-game launcher that Steam runs.
#
# The launcher is a thin shim: it carries only the Steam environment fixes, which
# never change, and hands off to `gotg play`. Keeping the logic in one place means
# fixing a bug does not mean regenerating every script anyone already added to
# Steam.

launcher_path() {
  local game="$1" id platform
  id="$(manifest_field "$game" id)"
  platform="$(manifest_field "$game" platform)"
  validate_id "$id"
  validate_platform "$platform"
  printf '%s/%s/play-%s.sh' "$GOTG_GAMES_DIR" "$platform" "$id"
}

# The argument the launcher passes back to `gotg play`. Qualified with the
# platform when the bare id would be ambiguous.
launcher_ref() {
  local game="$1" id platform count
  id="$(manifest_field "$game" id)"
  platform="$(manifest_field "$game" platform)"
  count="$(manifest_games | jq -s --arg id "$id" '[.[] | select(.id == $id)] | length')"
  if [[ "$count" -gt 1 ]]; then
    printf '%s/%s' "$platform" "$id"
  else
    printf '%s' "$id"
  fi
}

launcher_write() {
  local game="$1" dest template id title ref
  dest="$(launcher_path "$game")"
  template="$GOTG_TEMPLATES/launcher.sh.tpl"
  [[ -f "$template" ]] || die "missing launcher template at $template"

  id="$(manifest_field "$game" id)"
  title="$(sanitize_title "$(manifest_field "$game" title)")"
  : "${title:=$id}"
  ref="$(launcher_ref "$game")"

  # Back up a launcher we did not write, so a hand-tuned script is never lost.
  if [[ -e "$dest" ]] && ! grep -q 'generated by gotg' "$dest"; then
    mv "$dest" "$dest.bak"
    warn "kept your existing script as $(basename "$dest").bak"
  fi

  # Substitute with bash string replacement, not sed. Titles are free-form text
  # from the catalog: 45 games in this library have "&" in the title, which sed
  # expands to the matched text, and a title containing the delimiter or a
  # backslash escape aborts sed outright — after the redirection has already
  # truncated the destination.
  local content
  content="$(cat "$template")"
  content="${content//@ID@/$(escape_replacement "$id")}"
  content="${content//@REF@/$(escape_replacement "$ref")}"
  content="${content//@TITLE@/$(escape_replacement "$title")}"
  content="${content//@FLAKE@/$(escape_replacement "$(gotg_flake)")}"

  mkdir -p "$(dirname "$dest")"
  printf '%s\n' "$content" >"$dest"
  chmod +x "$dest"
  printf '%s' "$dest"
}
