# shellcheck shell=bash
# Generating the per-game launcher that Steam runs.
#
# The launcher is a thin shim: it carries only the Steam environment fixes, which
# never change, and hands off to `gotg play`. Keeping the logic in one place means
# fixing a bug does not mean regenerating every script anyone already added to
# Steam.

launcher_path() {
  local game="$1" id platform
  id="$(manifest_field "$game" id)"
  platform="$(manifest_field "$game" platform)"
  printf '%s/%s/play-%s.sh' "$GOTG_GAMES_DIR" "$platform" "$id"
}

# The argument the launcher passes back to `gotg play`. Qualified with the
# platform when the bare id would be ambiguous.
launcher_ref() {
  local game="$1" id platform count
  id="$(manifest_field "$game" id)"
  platform="$(manifest_field "$game" platform)"
  count="$(manifest_games | jq -s --arg id "$id" '[.[] | select(.id == $id)] | length')"
  if [[ "$count" -gt 1 ]]; then
    printf '%s/%s' "$platform" "$id"
  else
    printf '%s' "$id"
  fi
}

launcher_write() {
  local game="$1" dest template id title ref
  dest="$(launcher_path "$game")"
  template="$GOTG_TEMPLATES/launcher.sh.tpl"
  [[ -f "$template" ]] || die "missing launcher template at $template"

  id="$(manifest_field "$game" id)"
  title="$(manifest_field "$game" title)"
  : "${title:=$id}"
  ref="$(launcher_ref "$game")"

  # Back up a launcher we did not write, so a hand-tuned script is never lost.
  if [[ -e "$dest" ]] && ! grep -q 'generated by gotg' "$dest"; then
    mv "$dest" "$dest.bak"
    warn "kept your existing script as $(basename "$dest").bak"
  fi

  mkdir -p "$(dirname "$dest")"
  sed -e "s|@ID@|$id|g" \
    -e "s|@REF@|$ref|g" \
    -e "s|@TITLE@|$title|g" \
    -e "s|@FLAKE@|$(gotg_flake)|g" \
    "$template" >"$dest"
  chmod +x "$dest"
  printf '%s' "$dest"
}
